spring:
  config:
    activate:
      on-profile: "security"

oauth:
  google:
    client:
      id: ${GOOGLE_CLIENT_ID}
      secret: ${GOOGLE_CLIENT_SECRET}
      redirectUri: ${GOOGLE_REDIRECT_URI}
      grantType: ${GOOGLE_GRANT_TYPE}

  discord:
    client:
      id: ${DISCORD_CLIENT_ID}
      secret: ${DISCORD_CLIENT_SECRET}
      redirectUri: ${DISCORD_REDIRECT_URI}
      botToken: ${DISCORD_BOT_TOKEN}

  figma:
    client:
      id: ${FIGMA_CLIENT_ID}
      secret: ${FIGMA_CLIENT_SECRET}
      redirectUri: ${FIGMA_REDIRECT_URI}
      grantType: ${FIGMA_GRANT_TYPE}


jwt:
  access-token-secret: ${JWT_ACCESS_TOKEN}
  refresh-token-secret: ${JWT_REFRESH_TOKEN}
  access-token-expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
  refresh-token-expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME}
  issuer: ${JWT_ISSUER}
